### ISSUE TITLE
New installation method: bintray.com/rabbitmq-erlang

### ISSUE THREAD

**Issue by michaelklishin** [sous-chefs/erlang#67]
Would the maintainers of this cookbook consider a contribution that adds a new installation method that uses Bintray? Team RabbitMQ has been producing Debian and RPM packages of every patch release of OTP for the last several months. In our experience, this greatly improves latest patch version availability since ESL packages lag behind (a little birdie tells me because the process is not completely automated).

The [Debian package](https://github.com/rabbitmq/erlang-debian-package/) is available for several distributions and is based on the official Debian packages.

The RPM package is [stripped down](https://github.com/rabbitmq/erlang-rpm) and has an implicit OpenSSL dependency but nonetheless works well in practice for a lot of software, and significantly improves recent OTP patch release availability for RPM users.

I'd be happy to work on this if this has a chance of being accepted.

**Comment by michaelklishin** [comment]
I think it can be used with `openssl` alternatives but not 100% sure. The dependency is implicit exactly because we didn't want to pin ourselves to a single version series/flavor since RPM distributions are all over the place and we still support CentOS 6, for example. This is something to investigate.

I'm happy to implement it as a custom resource.

**Comment by michaelklishin** [comment]
@majormoses @tas50 I should have a chance to investigate it in the next couple of weeks. Is there a Chef-maintained cookbook that is somewhat similar and uses a custom resource I could learn from? I'm not very up-to-date with latest Chef practices and would appreciate a nudge in the right direction to save everyone some time.

**Comment by majormoses** [comment]
One I wrote relatively recently was https://github.com/majormoses/atlantis-chef which has some similar concepts in terms of writing a custom resource for multiple types of init subsystems. I think that translates well to install methods. While its a relatively simple cookbook I think it's a good reference point because its so simple; it's basically broken down into installation, configuration, and service management. It does not try to do any fancy checking as its intended to be a library cookbook and meant to be consumed by a wrapper where all the implementation details can live. I would say another good one (despite its tons of options) would be the [ark cookbook](https://github.com/chef-cookbooks/ark) that being said its really a single resource with a bunch of actions rather than multiple resources with one or more actions.
